#############################################################################
# Makefile for building: test
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  test.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile test.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe --sysroot= -O2 -std=gnu++1z -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Isrc -Imodel -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = test1.0.0
DISTDIR = /home/sitachan/tmp/test/.tmp/test1.0.0
LINK          = g++
LFLAGS        = --sysroot= -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		src/Color.cpp \
		src/Fonts.cpp \
		src/Renderer3D.cpp \
		src/font_tgx_Arial.cpp \
		src/font_tgx_Arial_Bold.cpp \
		src/font_tgx_OpenSans.cpp \
		src/font_tgx_OpenSans_Bold.cpp \
		src/font_tgx_OpenSans_Italic.cpp \
		widget.cpp moc_widget.cpp
OBJECTS       = main.o \
		Color.o \
		Fonts.o \
		Renderer3D.o \
		font_tgx_Arial.o \
		font_tgx_Arial_Bold.o \
		font_tgx_OpenSans.o \
		font_tgx_OpenSans_Bold.o \
		font_tgx_OpenSans_Italic.o \
		widget.o \
		moc_widget.o
DIST          = mesh-1.obj \
		mesh.obj \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		test.pro model/coffee_cup.h \
		model/coffee_cup_2_texture.h \
		model/coffee_cup_texture.h \
		src/Box2.h \
		src/Box3.h \
		src/Color.h \
		src/Color.inl \
		src/Fonts.h \
		src/Image.h \
		src/Image.inl \
		src/Mat4.h \
		src/Mesh3D.h \
		src/Mesh3D.inl \
		src/Misc.h \
		src/Rasterizer.h \
		src/Renderer3D.h \
		src/Renderer3D.inl \
		src/ShaderParams.h \
		src/Shaders.h \
		src/Vec2.h \
		src/Vec3.h \
		src/Vec4.h \
		src/bseg.h \
		src/font_tgx_Arial.h \
		src/font_tgx_Arial_Bold.h \
		src/font_tgx_OpenSans.h \
		src/font_tgx_OpenSans_Bold.h \
		src/font_tgx_OpenSans_Italic.h \
		src/tgx.h \
		src/tgx_config.h \
		widget.h main.cpp \
		src/Color.cpp \
		src/Fonts.cpp \
		src/Renderer3D.cpp \
		src/font_tgx_Arial.cpp \
		src/font_tgx_Arial_Bold.cpp \
		src/font_tgx_OpenSans.cpp \
		src/font_tgx_OpenSans_Bold.cpp \
		src/font_tgx_OpenSans_Italic.cpp \
		widget.cpp
QMAKE_TARGET  = test
DESTDIR       = 
TARGET        = test


first: all
####### Build rules

test: ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: test.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		test.pro
	$(QMAKE) -o Makefile test.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
test.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile test.pro

qmake_all: FORCE


all: Makefile test

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents model/coffee_cup.h model/coffee_cup_2_texture.h model/coffee_cup_texture.h src/Box2.h src/Box3.h src/Color.h src/Color.inl src/Fonts.h src/Image.h src/Image.inl src/Mat4.h src/Mesh3D.h src/Mesh3D.inl src/Misc.h src/Rasterizer.h src/Renderer3D.h src/Renderer3D.inl src/ShaderParams.h src/Shaders.h src/Vec2.h src/Vec3.h src/Vec4.h src/bseg.h src/font_tgx_Arial.h src/font_tgx_Arial_Bold.h src/font_tgx_OpenSans.h src/font_tgx_OpenSans_Bold.h src/font_tgx_OpenSans_Italic.h src/tgx.h src/tgx_config.h widget.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp src/Color.cpp src/Fonts.cpp src/Renderer3D.cpp src/font_tgx_Arial.cpp src/font_tgx_Arial_Bold.cpp src/font_tgx_OpenSans.cpp src/font_tgx_OpenSans_Bold.cpp src/font_tgx_OpenSans_Italic.cpp widget.cpp $(DISTDIR)/
	$(COPY_FILE) --parents widget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe --sysroot= -O2 -std=gnu++1z -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp
moc_widget.cpp: widget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QWidget \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringliteral.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpainterpath.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/QTimer \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtimer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasictimer.h \
		src/tgx.h \
		src/Fonts.h \
		src/Misc.h \
		src/tgx_config.h \
		src/Vec2.h \
		src/Box2.h \
		src/Vec3.h \
		src/Vec4.h \
		src/Mat4.h \
		src/Box3.h \
		src/Color.h \
		src/Color.inl \
		src/Image.h \
		src/ShaderParams.h \
		src/Shaders.h \
		src/Rasterizer.h \
		src/bseg.h \
		src/Image.inl \
		src/Mesh3D.h \
		src/Mesh3D.inl \
		src/Renderer3D.h \
		src/Renderer3D.inl \
		model/coffee_cup.h \
		model/coffee_cup_texture.h \
		model/coffee_cup_2_texture.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sitachan/tmp/test/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sitachan/tmp/test -I/home/sitachan/tmp/test/src -I/home/sitachan/tmp/test/model -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/opt/poky/3.1.20/sysroots/aarch64-poky-linux/usr/include/c++/8.3.0 -I/opt/poky/3.1.20/sysroots/aarch64-poky-linux/usr/include/c++/8.3.0/aarch64-poky-linux -I/opt/poky/3.1.20/sysroots/aarch64-poky-linux/usr/include/c++/8.3.0/backward -I/opt/poky/3.1.20/sysroots/x86_64-pokysdk-linux/usr/lib/aarch64-poky-linux/gcc/aarch64-poky-linux/8.3.0/include -I/opt/poky/3.1.20/sysroots/aarch64-poky-linux/usr/local/include -I/opt/poky/3.1.20/sysroots/x86_64-pokysdk-linux/usr/lib/aarch64-poky-linux/gcc/aarch64-poky-linux/8.3.0/include-fixed -I/opt/poky/3.1.20/sysroots/aarch64-poky-linux/usr/include widget.h -o moc_widget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h
ui_widget.h: widget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QApplication \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringliteral.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qeventloop.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpainterpath.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qguiapplication.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qinputmethod.h \
		widget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QWidget \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/QTimer \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtimer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasictimer.h \
		src/tgx.h \
		src/Fonts.h \
		src/Misc.h \
		src/tgx_config.h \
		src/Vec2.h \
		src/Box2.h \
		src/Vec3.h \
		src/Vec4.h \
		src/Mat4.h \
		src/Box3.h \
		src/Color.h \
		src/Color.inl \
		src/Image.h \
		src/ShaderParams.h \
		src/Shaders.h \
		src/Rasterizer.h \
		src/bseg.h \
		src/Image.inl \
		src/Mesh3D.h \
		src/Mesh3D.inl \
		src/Renderer3D.h \
		src/Renderer3D.inl \
		model/coffee_cup.h \
		model/coffee_cup_texture.h \
		model/coffee_cup_2_texture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Color.o: src/Color.cpp src/Color.h \
		src/Misc.h \
		src/tgx_config.h \
		src/Vec3.h \
		src/Vec2.h \
		src/Vec4.h \
		src/Color.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Color.o src/Color.cpp

Fonts.o: src/Fonts.cpp src/Fonts.h \
		src/Misc.h \
		src/tgx_config.h \
		src/Vec2.h \
		src/Box2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Fonts.o src/Fonts.cpp

Renderer3D.o: src/Renderer3D.cpp src/Renderer3D.h \
		src/Misc.h \
		src/tgx_config.h \
		src/Color.h \
		src/Vec3.h \
		src/Vec2.h \
		src/Vec4.h \
		src/Color.inl \
		src/Box2.h \
		src/Box3.h \
		src/Mat4.h \
		src/Image.h \
		src/Fonts.h \
		src/ShaderParams.h \
		src/Shaders.h \
		src/Rasterizer.h \
		src/bseg.h \
		src/Image.inl \
		src/Mesh3D.h \
		src/Mesh3D.inl \
		src/Renderer3D.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Renderer3D.o src/Renderer3D.cpp

font_tgx_Arial.o: src/font_tgx_Arial.cpp src/font_tgx_Arial.h \
		src/tgx.h \
		src/Fonts.h \
		src/Misc.h \
		src/tgx_config.h \
		src/Vec2.h \
		src/Box2.h \
		src/Vec3.h \
		src/Vec4.h \
		src/Mat4.h \
		src/Box3.h \
		src/Color.h \
		src/Color.inl \
		src/Image.h \
		src/ShaderParams.h \
		src/Shaders.h \
		src/Rasterizer.h \
		src/bseg.h \
		src/Image.inl \
		src/Mesh3D.h \
		src/Mesh3D.inl \
		src/Renderer3D.h \
		src/Renderer3D.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o font_tgx_Arial.o src/font_tgx_Arial.cpp

font_tgx_Arial_Bold.o: src/font_tgx_Arial_Bold.cpp src/font_tgx_Arial_Bold.h \
		src/tgx.h \
		src/Fonts.h \
		src/Misc.h \
		src/tgx_config.h \
		src/Vec2.h \
		src/Box2.h \
		src/Vec3.h \
		src/Vec4.h \
		src/Mat4.h \
		src/Box3.h \
		src/Color.h \
		src/Color.inl \
		src/Image.h \
		src/ShaderParams.h \
		src/Shaders.h \
		src/Rasterizer.h \
		src/bseg.h \
		src/Image.inl \
		src/Mesh3D.h \
		src/Mesh3D.inl \
		src/Renderer3D.h \
		src/Renderer3D.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o font_tgx_Arial_Bold.o src/font_tgx_Arial_Bold.cpp

font_tgx_OpenSans.o: src/font_tgx_OpenSans.cpp src/font_tgx_OpenSans.h \
		src/tgx.h \
		src/Fonts.h \
		src/Misc.h \
		src/tgx_config.h \
		src/Vec2.h \
		src/Box2.h \
		src/Vec3.h \
		src/Vec4.h \
		src/Mat4.h \
		src/Box3.h \
		src/Color.h \
		src/Color.inl \
		src/Image.h \
		src/ShaderParams.h \
		src/Shaders.h \
		src/Rasterizer.h \
		src/bseg.h \
		src/Image.inl \
		src/Mesh3D.h \
		src/Mesh3D.inl \
		src/Renderer3D.h \
		src/Renderer3D.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o font_tgx_OpenSans.o src/font_tgx_OpenSans.cpp

font_tgx_OpenSans_Bold.o: src/font_tgx_OpenSans_Bold.cpp src/font_tgx_OpenSans_Bold.h \
		src/tgx.h \
		src/Fonts.h \
		src/Misc.h \
		src/tgx_config.h \
		src/Vec2.h \
		src/Box2.h \
		src/Vec3.h \
		src/Vec4.h \
		src/Mat4.h \
		src/Box3.h \
		src/Color.h \
		src/Color.inl \
		src/Image.h \
		src/ShaderParams.h \
		src/Shaders.h \
		src/Rasterizer.h \
		src/bseg.h \
		src/Image.inl \
		src/Mesh3D.h \
		src/Mesh3D.inl \
		src/Renderer3D.h \
		src/Renderer3D.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o font_tgx_OpenSans_Bold.o src/font_tgx_OpenSans_Bold.cpp

font_tgx_OpenSans_Italic.o: src/font_tgx_OpenSans_Italic.cpp src/font_tgx_OpenSans_Italic.h \
		src/tgx.h \
		src/Fonts.h \
		src/Misc.h \
		src/tgx_config.h \
		src/Vec2.h \
		src/Box2.h \
		src/Vec3.h \
		src/Vec4.h \
		src/Mat4.h \
		src/Box3.h \
		src/Color.h \
		src/Color.inl \
		src/Image.h \
		src/ShaderParams.h \
		src/Shaders.h \
		src/Rasterizer.h \
		src/bseg.h \
		src/Image.inl \
		src/Mesh3D.h \
		src/Mesh3D.inl \
		src/Renderer3D.h \
		src/Renderer3D.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o font_tgx_OpenSans_Italic.o src/font_tgx_OpenSans_Italic.cpp

widget.o: widget.cpp widget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QWidget \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qconfig.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtcore-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsystemdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qprocessordetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcompilerdetection.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtypeinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsysinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlogging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qgenericatomic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_msvc.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobalstatic.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnumeric.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qversiontagging.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtgui-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qnamespace.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qarraydata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringliteral.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringview.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringbuilder.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qalgorithms.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiterator.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpair.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearraylist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringlist.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qregexp.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qstringmatcher.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcoreevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontainerfwd.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmargins.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpaintdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qrect.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsize.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qpoint.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpalette.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcolor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgb.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qrgba64.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qbrush.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpolygon.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qiodevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qline.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpainterpath.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixelformat.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpixmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfont.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontmetrics.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qfontinfo.h \
		/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qcursor.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qkeysequence.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qset.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qcontiguouscache.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurl.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qurlquery.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfile.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qfiledevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qvector2d.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtouchdevice.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/QTimer \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qtimer.h \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/qbasictimer.h \
		src/tgx.h \
		src/Fonts.h \
		src/Misc.h \
		src/tgx_config.h \
		src/Vec2.h \
		src/Box2.h \
		src/Vec3.h \
		src/Vec4.h \
		src/Mat4.h \
		src/Box3.h \
		src/Color.h \
		src/Color.inl \
		src/Image.h \
		src/ShaderParams.h \
		src/Shaders.h \
		src/Rasterizer.h \
		src/bseg.h \
		src/Image.inl \
		src/Mesh3D.h \
		src/Mesh3D.inl \
		src/Renderer3D.h \
		src/Renderer3D.inl \
		model/coffee_cup.h \
		model/coffee_cup_texture.h \
		model/coffee_cup_2_texture.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/QPainter \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpainter.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qtextoption.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/qpen.h \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/QPaintEvent \
		/usr/include/x86_64-linux-gnu/qt5/QtGui/QResizeEvent \
		/usr/include/x86_64-linux-gnu/qt5/QtCore/QtGlobal
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/test/bin || mkdir -p $(INSTALL_ROOT)/opt/test/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/test/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/test/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/test/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/test/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

